-- Migración: Agregar columnas SMTP a crm_settings
-- Fecha: 2025-12-03

ALTER TABLE crm_settings 
ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255),
ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT 587,
ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255),
ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255),
ADD COLUMN IF NOT EXISTS smtp_secure BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255) DEFAULT 'NoahPro CRM',
ADD COLUMN IF NOT EXISTS smtp_from_email VARCHAR(255);
